# =================================================================== 
# Spring Boot default configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# =================================================================== 

# =================================================================== 
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# =================================================================== 

# =================================================================== 
# Logging properties
# =================================================================== 

logging:
  config: classpath:log4j2.yml

# =================================================================== 
# Server properties
# =================================================================== 

server:
  port: 8080
  servlet:
    context-path: /

# =================================================================== 
# Spring specific properties
# =================================================================== 

spring:

  profiles:
    default: dev
    
  datasource:
    url: jdbc:postgresql://localhost:5432/avoristech
    username: avoristech
    password: avotistech
    hikari:
      driver-class-name: org.postgresql.Driver
  
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: avoristech

  h2:
    console.enabled: true
    
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: searches_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: es.mindata.avoristech.domain.SearchEntity

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.add.type.headers: false

  jackson:
    dateFormat: dd/MM/yyyy
    default-property-inclusion: non-null
